# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  # config.vm.network "private_network", ip: "192.168.1.88"


  config.vm.box_check_update = false


  config.vm.synced_folder "/home/kazamel/Documents/projects/devops/docker_labs", "/opt/vagrant", type: "rsync" 


  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = 'esxi'
    esxi.esxi_username = 'root'

    #  IMPORTANT!  Set ESXi password.
    #    1) 'prompt:'
    #    2) 'file:'  or  'file:my_secret_file'
    #    3) 'env:'  or 'env:my_secret_env_var'
    #    4) 'key:'  or  key:~/.ssh/some_ssh_private_key'
    #    5) or esxi.esxi_password = 'my_esxi_password'

    esxi.esxi_password = ENV['ESXI_PASSWORD']
    esxi.esxi_disk_store = "datastore1"
    esxi.esxi_virtual_network = ["VM Network"]

    esxi.guest_memsize = '2048'
    esxi.guest_numvcpus = '2'
    esxi.guest_name = "ubuntu-22"

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", path: "provision.sh" , run: "once"

    
end
