# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "ubuntu/jammy64"

  config.vm.box = "generic/ubuntu2204"


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.1.88"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  #  config.vm.network "public_network"
   # Disable automatic box update checking. If you disable this, then
   # boxes will only be checked for updates when the user runs
   # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false



  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  
  # Windows Path
  # config.vm.synced_folder "F:\\scripts\\shellscripts", "/opt/scripts"
   
  # MacOS
  config.vm.synced_folder("/home/kazamel/Documents/projects/vagrant/ubuntu-22", "/opt/vagrant", type: "rsync" )

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  #  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #

  # config.vm.box_version = "20260526.0"
  #
  #  Provider (esxi) settings
  #
  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = 'esxi'
    esxi.esxi_username = 'root'

    #  IMPORTANT!  Set ESXi password.
    #    1) 'prompt:'
    #    2) 'file:'  or  'file:my_secret_file'
    #    3) 'env:'  or 'env:my_secret_env_var'
    #    4) 'key:'  or  key:~/.ssh/some_ssh_private_key'
    #    5) or esxi.esxi_password = 'my_esxi_password'
    #
    # esxi.esxi_password = 'prompt:'

    # esxi.esxi_password = 'your_password or use prompt:'

    esxi.esxi_disk_store = "datastore1"
    esxi.esxi_virtual_network = ["VM Network"]


    # Customize the amount of memory on the VM:

    esxi.guest_memsize = '2048'
    esxi.guest_numvcpus = '2'
    esxi.guest_name = "ubuntu-22"

  end

 
  
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     

     
     sudo apt-get update
     mkdir -p /opt/vagrant
     free -m >> /opt/vagrant/ram.txt
     df -h >> /opt/vagrant/disk.txt
     sudo apt-get install -y apache2
    #  sudo apt install sshfs -y   
    #  sudo apt install nfs-common -y
    #  sudo shfs kazamel@kazamel-hp:/home/kazamel/Documents/projects/vagrant/vagrantAndLinuxServers/ubuntos /opt/vagrant
   SHELL
end
