Vagrant.configure("2") do |config|

  config.vm.box = "generic/rocky9"
  config.vm.network "private_network", ip: "192.168.1.50"
  config.vm.network "public_network"
  config.vm.synced_folder "./portfolio/", "/var/www/html/" , type: "rsync"

  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = 'esxi'
    esxi.esxi_username = 'root'
    # esxi.esxi_password = 'prompt:'
    # esxi.esxi_password = 'your_password or use prompt:'
    esxi.esxi_disk_store = "datastore1"
    #esxi.esxi_virtual_network = ["VM Network"]
    esxi.guest_memsize = '2048'
    esxi.guest_numvcpus = '2'
    esxi.guest_name = "rocky-9"
  end


  config.vm.provision "shell", inline: <<-SHELL
     sudo yum update -y

     mkdir -p /opt/vagrant
     free -m >> /opt/vagrant/ram.txt
     df -h >> /opt/vagrant/disk.txt

     sudo yum install -y httpd 
     sudo yum install wget vim unzip zip -y -y

     sudo systemctl start httpd
     sudo systemctl enable httpd 

     sudo systemctl stop firewalld
     sudo systemctl disable firewalld
     sudo systemctl mask --now firewalld    
   SHELL

end
