Vagrant.configure("2") do |config|

  config.vm.box = "generic/rocky9"
  config.vm.network "private_network", ip: "192.168.1.55"
  config.vm.network "public_network"
  config.vm.synced_folder "./portfolio/", "/var/www/html/" ,  type: 'nfs', disabled: true
  # , type: "rsync"
  # config.vm.network "forwarded_port", guest: 80, host: 9080

  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = 'esxi'
    esxi.esxi_username = 'root'
    # esxi.esxi_password = 'prompt:'
    esxi.esxi_password = ENV['ESXI_PASSWORD']
    # esxi.esxi_password = $ESXI_PASSWORD // vagrant bug , refusing @ sympol in password
    esxi.esxi_disk_store = "datastore1"
    #esxi.esxi_virtual_network = ["VM Network"]
    esxi.guest_memsize = '1024'
    esxi.guest_numvcpus = '2'
    esxi.guest_name = "rocky-IAC"
  end


  config.vm.provision "shell", path: "provision.sh" , run: "always"

end
